import {
    ICredentialType,
    INodeProperties,
} from 'n8n-workflow';

export class ICloudApi implements ICredentialType {
    name = 'iCloudApi';
    displayName = 'iCloud API';
    documentationUrl = 'https://github.com/swaynos/n8n-nodes-icloud-drive-tools';
    properties: INodeProperties[] = [
        {
            displayName: 'Session JSON',
            name: 'sessionJson',
            type: 'string',
            typeOptions: {
                password: true,
            },
            default: '',
            description: 'The session JSON string generated by the helper script.',
        },
    ];
}
